
services:
  db:
    image: mysql:5.7
    container_name: todo_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todo_db
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    restart: always

  backend:
    build: ./backend
    container_name: todo_backend
    depends_on:
      - db
    ports:
      - "8000:8000"
    restart: always

  frontend:
    build: ./frontend
    container_name: todo_frontend
    ports:
      - "80:80"
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: todo_phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8080:80"
    depends_on:
      - db
    restart: always

volumes:
  db-data:
         